dongbaek/church/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name ='church'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='church'),
]

dongbaek/dongbaek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(
        pattern_name = 'instagram:post_list',
        ), name='root'),
    path('admin/', admin.site.urls),
    path('inflearn/', include('inflearn.urls')),
    path('instagram/', include('instagram.urls')),
    path('church/', include('church.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

dongbaek/instagram/urls.py
from . import views
from django.urls import path, re_path, register_converter
from .converters import YearConverter, MonthConverter, DayConverter

register_converter(YearConverter, 'year')
register_converter(MonthConverter, 'Month')
register_converter(DayConverter, 'Day')

app_name = 'instagram' # URL Reverse에서 namespace 역할을 하게 된다.

urlpatterns = [ 
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'), # Post.DoesNotExist 오류

    
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'), # Post.DoesNotExist 오류
    # 숫자 타입이 나오고, /로 끝날경우 뒤 함수를 호출하겠다는의미

    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year:year>/', views.post_archive_year, name='post_archive_year'),
    #path('archive/<year:year>/<month:month>/', views.post_archive_month, name='post_archive_month'),
    #path('archive/<year:year>/<month:month>/<day:day>/', views.post_archive_day, name='post_archive_day'),

]

dongbaek/instagram/models.py
from http import server
from django.conf import settings
from django.contrib.admin.decorators import register
from django.db import models
from django.db.models.fields.related import ManyToManyField
from django.urls import reverse

from django.core.validators import MinLengthValidator

# validators 객체는 함수를 반환하여준다.
# 만약 3글자 미만의 문자열을 입력받으면 forms.ValidationError를 반환한다.
min_length_Validators = MinLengthValidator(3)




# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)
    message = models.TextField(
        validators=[min_length_Validators]
    )
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y/%m/%d')
    tag_set = models.ManyToManyField('Tag', blank=True)
    # Tag를 문자열로 적은 이유는, Tag Class가 맨 아래 있기 때문에 참조하는데 있어서 오류가 생기기 때문이다.
    # blank는 Tag가 없는 상황을 허용할건지 (True)를 물어보는 인자 옵션이다. 
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    # Java의 toString과 같은 역할
    def __str__(self):
        return self.message
    
    # id의 역순으로 정렬함.
    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, limit_choices_to={'is_public': True}) # post_id 필드가 생성
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True) # 태그는 해당 태그 테이블 내에서 유일해야 하기에 unique 사용
    #post_set = models.ManyToManyField(Post) # reverse 방법
    
    def __str__(self):
        return self.name

dongbaek/instagram/forms.py
from dataclasses import field
import re
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'message', 'photo', 'tag_set', 'is_public'
        ]
        
    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message: 
            message = re.sub(r'[a-zA-Z]+', '', message) # 영어를 공백으로 바꿔준다.
        return message

dongbaek/instagram/views.py
from urllib import request
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models.base import Model
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import ArchiveIndexView, DetailView
from django.views.generic.dates import YearArchiveView
from django.views.generic.list import ListView

from .forms import PostForm
from .models import Post

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user # 현재 로그인한 유저 Instance
            post.save()
            # post의 detail.html로 이동함.
            return redirect(post)
    else:         
        form = PostForm()
        
    return render(request, 'instagram/post_form.html',{
        'form' : form,
    })


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 이렇게 반복되는 코드가 있다면 장식자로 만드는 것도 좋은 방법
    # 작성자만 수정할 수 있도록 
    if post.author != request.user:
        messages.error(request, '작성자만 수정 가능합니다!')
        return redirect(post)


    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            # post의 detail.html로 이동함.
            return redirect(post)
    else:         
        form = PostForm(instance=post)
        
    return render(request, 'instagram/post_form.html',{
        'form' : form,
    })




@login_required
def post_list(request):
    # QuerySet을 의미함.
    qs = Post.objects.all()
    
    # 전달 받은 인자 중에서 'q'라는 이름의 인자를 가져오겠다는 의미
    # 두번째 매개변수는 만약 'q'라는 인자가 없을시 반환할 값을 의미
    # https://velog.io/@sdk1926/request.GET.getq
    q = request.GET.get('q', '')
    
    # 'q'라는 인자가 있었을 경우
    if q:
        #  filter를 통해서 message 필드 중 q인 필드들만 qs에 저장함.
        qs = qs.filter(message__icontains=q)
    
    # render를 통해서 HTML 응답을 쉽게 만들 수 있다.
    # render의 첫번째 인자는 view 함수의 인자를 넘겨받는다.
    # 두번째 인자는 app이름을 써주고 뒤에 원하는 템플릿(HTML) 이름을 써준다.
    # 세번쨰 인자로 템플릿 내에서 참조할 것과 참조할 이름을 적어준다.
    
    # 위치는 instagram(app)/templates/instagram/post_list.html
    return render(request, 'instagram/post_list.html', {
        'post_list': qs,
        'q' : q,
    })


# post_list = ListView.as_view(model=Post, paginate_by= 10)
@method_decorator(login_required, name='dispatch')
class PostListView(ListView):
    model = Post
    paginate_by = 10


post_list = PostListView.as_view()


post_detail = DetailView.as_view(
    model = Post,
    queryset = Post.objects.all()
)


post_archive = ArchiveIndexView.as_view(model= Post , date_field='created_at')

post_archive_year = YearArchiveView.as_view(model= Post, date_field='created_at', make_object_list=True)

dongbaek/instagram/templates/instagram/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock title %} </title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.2-dist/css/bootstrap.css' %}" />
    <script src="{% static 'jquery.csrf.js' %}"></script>
    <script src="{% static 'jquery-3.6.0.min.js' %}" ></script>
    <script src="{% static 'bootstrap-3.3.2-dist/js/bootstrap.js' %}"></script>
    <style>
        body{
            padding-top: 5rem;
            padding-bottom: 2rem;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">                 
        </div>
      </nav>
      
      <div class="container">
          <div class="row">
              <div class="col-sm-12">
                  {% block content %}
                  {% endblock content %}
      
                  <hr/>
                  &copy; Dongbaek
              </div>
          </div>
      </div>
</body>
</html>

dongbaek/instagram/templates/instagram/post_archive.html
<h2>latest</h2>

{{ latest }}

<h2>date_list</h2>

{% for date in date_list %}
    {{date.year}}
{% endfor %}

dongbaek/instagram/templates/instagram/post_archive_year.html
<h2> year </h2>
{{ year }}

<h2> previous year </h2>
{{ previous_year }}

<h2> next year </h2>
{{ next_year }}

<h2> object list </h2>
{{ object_list }}

dongbaek/instagram/templates/instagram/post_detail.html
{% extends "Instagram/layout.html"%}


{% block title %}
    Post  Detail pk#{{ post.pk }}
{% endblock title %}

{% block content %}
    <h2>Author : {{ post.author }}</h2>

    {% if post.photo %}
        <div>
            <img src="{{ post.photo.url }}" />
        </div>
    {% endif %}

    {{ post.message }}
    <hr/>
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>
{% endblock content %}

dongbaek/instagram/templates/instagram/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="저장" />
</form>

dongbaek/instagram/templates/instagram/post_list.html
{% extends "Instagram/layout.html"%}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post List
{% endblock title %}

{% block content %}       
    <form action="" method="get">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="검색" />
    </form>

    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-4 mb-4">새 포스팅</a>

    <table class="table table-borderd table-hover">
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>
                        {{ post.pk }}
                    </td>
                    <td>
                        {% if post.photo %}
                            <img src="{{ post.photo.url }}" style="width: 100px;"/>
                        {% else %}
                            No Photo    
                        {% endif %}
                    </td>
                    <td>
                        <a href= "{{ post.get_absolute_url }}" >
                        {{ post.message }}       
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {{ is_paginated }}
    {{ page_obj }}
    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="small" justify_content="center" %}
    {% endif %}
{% endblock content %}
    