django_instagram/insta/urls.py
from django.urls import path, re_path
from django.contrib.auth.validators import UnicodeUsernameValidator

from . import views

# reverse에 사용할 이름
app_name = 'insta'

# 주소에 오는 username이 Unicode 형태인지 확인하는 Validator 
# username_regax = UnicodeUsernameValidator.regex.lstrip('^').strip('$')

urlpatterns = [
    path('', views.index, name='index'),

    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    # 아래 path에서는 comment가 주인공이기에 post_pk로 작성
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),

    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),    
    ]

django_instagram/instagram/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from django_pydenticon.views import image as pydenticon_image


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/' , include('accounts.urls')),
    path('insta/', include('insta.urls')), 

    path('', RedirectView.as_view(pattern_name='insta:index'), name='root' ), # re_path를 사용하면 모든 주소에 매칭이 된다.
    path('identicon/images/<path:data>/', pydenticon_image, name='pydenticon_image'),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

django_instagram/insta/models.py
import re
from django.db import models
from django.urls import reverse

# User 외래키로 삼는 법
from django.conf import settings

class BaseModel(models.Model):

    class Meta:
        # 아래 코드를 통해 실제 DB에 적용되지 않고, 추상 클래스로 만들어진다.
        abstract = True


class Post(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="my_post_set", on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="insta/post/%Y%m%d")
    # 내용
    caption = models.TextField()
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set", blank=True)
    
    
    # Post 객체가 생성되면 아래 __str__함수가 호출된다.
    def __str__(self):
        return self.caption


    # 태그 기능
    def extract_tag_list(self):
        # "#"이 붙고 뒤에 문자가 오면 태그로 분류 저장한다.
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        
        # tag가 저장될 list
        tag_list = []
        
        # caption(본문)에서 #이 들어간 문자열을 TAG의 name에 저장해준다.
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    # detail view
    def get_absolute_url(self):
        return reverse("insta:post_detail", args=[self.pk])
    
    
    # 만약 유저가 포스팅을 좋아한다면(=like_user_set에 유저 pk가 있다면) True를 반환
    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()

    class Meta:
        ordering = ['-id']



class Comment(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

django_instagram/insta/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =  [
            'photo', 'caption', 'location'
        ]

        # 장고에서는 widgets 를 통해 특정 필드 위젯을 변경할 수 있다.
        widgets = {
            "caption" : forms.Textarea,
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["message"]

django_instagram/insta/views.py
from urllib import request
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q
from .forms import PostForm, CommentForm
from .models import Tag, Post

from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404


from datetime import timedelta
from django.utils import timezone

@login_required
def index(request):
    # 현재를 기준으로 3일 이내라면
    timesince = timezone.now() - timedelta(days=3)

    # TimeLine에 Follow하는 유저들의 포스팅 만을 노출하기
    post_list = Post.objects.all()\
        .filter( 
            Q(author=request.user) | 
            Q(author__in=request.user.following_set.all())
            )\
        .filter(
            #created_at__lte = timesince # 3일 이내의 게시글
            created_at__gte = timesince # 3일 이외의 게시글
        ) 
         
         

    #    Q는 or을 의미한다.
    #    .filter(
    #    # 작성자가 본인 또는
    #        Q(author=request.user)) |
    #
    #        # 유저의 following_set에 들어있는 유저만 보이도록
    #        Q(author__in=request.user.following_set.all()) 
    #    )
    #    


    #like_user_set = Post.like_user_set

    suggested_user_list = get_user_model().objects.all()\
        .exclude(pk=request.user.pk)\
        .exclude(pk__in=request.user.following_set.all())[:3] # 이미 팔로잉 하고 있는 유저들을 제외함.
        
    # 유저 본인 pk를 제외하고 나머지 유저가 suggested_user이다.
    return render(request, "insta/index.html", {
        #"like_user_set" : like_user_set,
        "post_list" : post_list,
        "suggested_user_list" : suggested_user_list,       
    })
    



# 포스팅 쓰기
@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            # 현재 로그인 유저를 작성자에 저장
            post.author = request.user
            # manytomany는 실제 pk 값이 있어야하기에 form이 저장된 상태로 해야한다.
            post.save()
            # post의 tag_list를 호출하여 Post 모델의 tag_set에 저장한다.
            post.tag_set.add(*post.extract_tag_list())

            messages.success(request, "포스팅을 저장했습니다.")
           
            # 모델 인스턴스의 get_absolute_url() 함수를 자동으로 호출
            # -> get_absolute_url() 함수에서 지정한 위치로 이동하게 된다.
            return redirect(post) 
    
    else:
        form = PostForm()

    return  render(request, "insta/post_form.html", {
        "form" : form,
    })


# 포스팅 detail
def post_detail(request, pk):
    # 해당 pk의 포스팅 객체가 없을 경우 404 에러 반환
    post = get_object_or_404(Post, pk=pk)
    return render(request, "insta/post_detail.html", {
        "post" : post,
    })


# 유저 페이지
def user_page(request, username):
    # 해당 글 작성자 객체 저장 
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    
    # 해당 유저가 쓴 글만을 filter 처리하여서 저장
    post_list = Post.objects.filter(author=page_user)
    post_list_cnt = post_list.count() # 실제 DB에 count 쿼리를 던짐
    
        # 로그인이 되어있으면 User 객체, or Not AnonymousUser  
    if request.user.is_authenticated:
        # 로그인이 되어있으면, Following_set의 작성자 pk가 존재하면 유저 객체를 가져온다.
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    return render(request, "insta/user_page.html", {
        "page_user": page_user,
        "post_list": post_list,
        "post_list_cnt": post_list_cnt,
        "is_follow": is_follow,
    })


# 포스팅 좋아요
@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    # like_user_set에 글 작성자(=request.user)를 추가해준다.
    post.like_user_set.add(request.user)

    messages.success(request, f"포스팅 {post.pk}를 좋아합니다.")
    
    redirect_url = request.META.get("HTTP_REFERER", "root") # HTTP_REFERER은 request 요청을 한 웹페이지의 주소를 보여준다.
    # 만약 HTTP_REFERER가 없으면 root 주소를 가져온다.
    return redirect(redirect_url)


# 포스팅 싫어요
@login_required
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    # like_user_set에 글 작성자(=request.user)를 제거해준다.
    post.like_user_set.remove(request.user)

    messages.success(request, f"포스팅 {post}의 좋아요를 취소합니다.")
    
    redirect_url = request.META.get("HTTP_REFERER", "root") # HTTP_REFERER은 request 요청을 한 웹페이지의 주소를 보여준다.
    # 만약 HTTP_REFERER가 없으면 root 주소를 가져온다.
    return redirect(redirect_url)


# 댓글 쓰기
@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # 내부적으로 comment가 save되는 것을 막음 
            # 그 이유는 댓글 폼은 message 필드만 받기 때문에, 나머지 필드에서 오류가 생기기 때문이다.
            # 그러기에 나머지 필드를 채워준 상태에서 form을 저장 시켜야한다.
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect(comment.post)    
    else:
        form = CommentForm()
    return render(request, "insta/comment_form.html", {
        "form" : form,
    })   

django_instagram/insta/templates/insta/_post_card.html
{% load bootstrap4 humanize insta_tags  %}

<div class="card">
    <div class="card-header">    
        <img src= "{{ user.profile_url }}" style="width: 24px; height: 24px;"/>
        <a href="{% url "insta:user_page" post.author.username %}" style="text-decoration:none">
            {{ post.author }}    
        </a>                
    </div>
    
    <div class="card-body">   
        {% if post.photo.url %}
            <img src="{{ post.photo.url  }}" style="width: 100%;"/>
        {% endif %}  
        <div>
            {% if post|is_like_user:user %}
                <a href="{% url 'insta:post_unlike' post.pk %}" style="text-decoration:none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FF0000" class="bi bi-heart-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                    </svg>
                </a>
            {% else %}
                <a href="{% url 'insta:post_like' post.pk %}" style="text-decoration:none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#FF0000" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                    </svg> 
                </a>
            {% endif %}
        </div>

        <div class="comment-list mt-3 mb-3">
            {% for comment in post.comment_set.all %}
            <div class="comment">
                <strong>{{ comment.author }}</strong>
                {{ comment.message }}
                <small class="text-muted">{{ comment.created_at|naturaltime }}</small>
            </div>
            {% endfor %}
        </div>

        <div>
            {% for tag in post.tag_set.all %}
                <span class="badge badge-primary" style="color: #fff;
                background-color: #007bff;">                        
                    #{{ tag.name }}
                </span>
            {% endfor %}  
        </div>         
        
        <div>
            <a href="{{ post.get_absolute_url }}" style="text-decoration:none" class="text-muted">
                <small>
                    {{ post.created_at|naturaltime }}
                </small>
            </a>
        </div>    
    </div>
    
    <div class="card-footer">                           
        <a href="{% url 'insta:comment_new' post.pk %}">
            댓글 쓰기
        </a>
    </div>
</div>    

django_instagram/insta/templates/insta/comment_form.html
{% extends "insta/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="새 댓글 쓰기" submit_label="새 댓글 쓰기"  %}
            </div>
        </div>
    </div>  
{% endblock %}

django_instagram/insta/templates/insta/index.html
{% extends "insta/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 mb-3">
                <a href="{% url 'insta:post_new' %}" class="btn btn-primary">새 포스팅 쓰기</a>             
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">     
                {% for post in post_list %}
                    <div class="mb-3">
                        <!-- include에는 /로 -->
                        {% include "insta/_post_card.html" %}
                    </div>    
                {% empty %}
                    포스팅이 없습니다.
                {% endfor %}
            </div>
            <div class="col-sm-4">
                {% include "insta/timeline_sidebar.html" %}
            </div>
        </div>
    </div>
{% endblock %}

django_instagram/insta/templates/insta/layout.html
{% extends "layout.html" %}

django_instagram/insta/templates/insta/post_detail.html
{% extends "insta/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "insta/_post_card.html" %}
            </div>
        </div>
    </div>  
{% endblock %}

django_instagram/insta/templates/insta/post_form.html
{% extends "insta/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="새 포스팅 쓰기" submit_label="새 포스팅 쓰기"  %}
            </div>
        </div>
    </div>  
{% endblock %}

django_instagram/insta/templates/insta/timeline_sidebar.html
<div class="d-flex p-2">
    <div class="mr-4">
        <img src="{{ user.profile_url }}" style="width: 40px; height: 40px;" class="rounded-circle"/>
    </div>
    <div>
        {{ user.username }}<br/>
        <small class="text-muted">{{ user.name }}</small>
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Stories
    </div>
    <div class="card-body text-muted">
        Stories from people you follow will show up
    </div>
</div>
            
<div class="card mb-2">
    <div class="card-header text-muted">
        Suggestions for you
    </div>
    <div class="card-body text-muted">
        {% for suggested_user in suggested_user_list %}
            {% include 'insta/timeline_sidebar_user_follow.html'%}
        {% empty %}
            추천 친구가 없습니다.
        {% endfor %} 
    </div>
</div>
            

django_instagram/insta/templates/insta/timeline_sidebar_user_follow.html
<div class="d-flex">
    <div class="mr-3">
        <img src="{{ suggested_user.profile_url }}" style="width: 32px; height: 32px;" class="rounded-circle"/>}
    </div>
    <div class="p-2">
        <a href="{% url "insta:user_page"  suggested_user.username %}">
            {{ suggested_user.username }}
        </a>
    </div>
    <div class="ml-auto">
        <a href="{% url "user_follow" suggested_user.username %}">Follow</a>
        <a href="{% url "user_unfollow" suggested_user.username %}">Unfollow</a>
    </div>
</div>

django_instagram/insta/templates/insta/user_page.html
{% extends "insta/layout.html" %}
{% load thumbnail %}

{% block content %}
    <div class="container">
        <div class="row pt-5 pb-5">
            <div class="col-sm-3" style="text-align: center;">
                <img src="{{ page_user.profile_url }}" class="rounded-circle" style="width: 160px;" />
            </div>
            <div class="col-sm-9">
                {{ page_user.username }}
                <a href="{% url "profile_edit" %}" class="btn btn-secondary btn-sm">
                    Edit Profile
                </a>
                                
                {% if is_follow %}
                    <!-- url로 이동시키되 뒤에 오는 문자열을 인자로 사용한다.  -->
                    <a href="{% url "user_unfollow" page_user.username %}">UnFollow</a>
                {% else %}
                    <a href="{% url "user_follow" page_user.username %}">Follow</a>
                {% endif %}

                <hr/>
                {{ post_list_cnt }} posts, 0 followers, 0 following
                <hr/>
                {{ page_user.name }}
            </div>
        </div>
        <div class="row mt-3">
            {% for post in post_list %}
                <div class="col-sm-4 mb-3">
                    <img src="{% thumbnail post.photo 256x256 crop %}" alt="{{ post.caption }}" style="width: 100%;%" />
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}